//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSBundle.h>

@class NSDate, NSString, NSURL;

@interface NSBundle (LicensingKitConfiguration)
@property(readonly) NSDate *preReleaseExpiryDate;
@property(readonly) unsigned long long trialPeriodDuration;
@property(readonly) NSString *EULADocumentPath;
@property(readonly) NSURL *licenseServerBaseURL;
@property(readonly) NSString *licenseWindowIcon;
@property(readonly) NSURL *productPageURL;
@end

