//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class NSButton, NSData, NSProgressIndicator, NSTextField, NSTextFieldCell, NSURLSessionDataTask, ZLicenseServer, ZLicenseWindowController;

@interface ZCheckingSubscriptionWindowController : NSWindowController
{
    ZLicenseServer *_licenseServer;
    NSData *_licenseKey;
    NSButton *_enterNewKeyButton;
    ZLicenseWindowController *_licenseWindowController;
    NSTextField *_subscriptionNotValidText;
    NSTextField *_renewLabel;
    NSTextField *_clickHereLabel;
    NSTextField *_dotLabel;
    NSTextField *_questionsLabel;
    NSTextField *_contactClickLabel;
    NSTextField *_supportTeamLabel;
    NSTextField *_cancelCloseLabel;
    NSTextField *_checkingSubscriptionLabel;
    NSTextField *_descriptionLabel;
    NSProgressIndicator *_spinner;
    NSTextFieldCell *_titleLabel;
    NSURLSessionDataTask *_activeTask;
    long long _numberOfConnectionRetries;
}

+ (id)instanceWithLicenseServer:(id)arg1 key:(id)arg2;
@property long long numberOfConnectionRetries; // @synthesize numberOfConnectionRetries=_numberOfConnectionRetries;
@property(retain, nonatomic) NSURLSessionDataTask *activeTask; // @synthesize activeTask=_activeTask;
@property __weak NSTextFieldCell *titleLabel; // @synthesize titleLabel=_titleLabel;
@property __weak NSProgressIndicator *spinner; // @synthesize spinner=_spinner;
@property __weak NSTextField *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property __weak NSTextField *checkingSubscriptionLabel; // @synthesize checkingSubscriptionLabel=_checkingSubscriptionLabel;
@property __weak NSTextField *cancelCloseLabel; // @synthesize cancelCloseLabel=_cancelCloseLabel;
@property __weak NSTextField *supportTeamLabel; // @synthesize supportTeamLabel=_supportTeamLabel;
@property __weak NSTextField *contactClickLabel; // @synthesize contactClickLabel=_contactClickLabel;
@property __weak NSTextField *questionsLabel; // @synthesize questionsLabel=_questionsLabel;
@property __weak NSTextField *dotLabel; // @synthesize dotLabel=_dotLabel;
@property __weak NSTextField *clickHereLabel; // @synthesize clickHereLabel=_clickHereLabel;
@property __weak NSTextField *renewLabel; // @synthesize renewLabel=_renewLabel;
@property __weak NSTextField *subscriptionNotValidText; // @synthesize subscriptionNotValidText=_subscriptionNotValidText;
@property(retain) ZLicenseWindowController *licenseWindowController; // @synthesize licenseWindowController=_licenseWindowController;
@property __weak NSButton *enterNewKeyButton; // @synthesize enterNewKeyButton=_enterNewKeyButton;
@property(retain, nonatomic) NSData *licenseKey; // @synthesize licenseKey=_licenseKey;
@property(retain, nonatomic) ZLicenseServer *licenseServer; // @synthesize licenseServer=_licenseServer;
- (void).cxx_destruct;
- (void)dismissIfModal:(BOOL)arg1 error:(id)arg2;
- (void)closeModalWindowWithStatus:(long long)arg1;
- (void)closeClick:(id)arg1;
- (void)contactClicked:(id)arg1;
- (void)renewClicked:(id)arg1;
- (void)subscriptionInvalid;
- (void)newKeyButtonClick:(id)arg1;
- (void)checkSubscription;
- (void)windowDidLoad;
- (id)init;

@end

