//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <LicensingKit/ZLicensingPolicy.h>

@class NSString;

@interface ZEULALicensingPolicy : ZLicensingPolicy
{
    NSString *preferenceKey;
    NSString *documentPath;
}

+ (id)EULALicensingPolicy;
@property(retain, nonatomic) NSString *documentPath; // @synthesize documentPath;
@property(retain, nonatomic) NSString *preferenceKey; // @synthesize preferenceKey;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)preferenceKeyChanged;
- (BOOL)applyWithUserInterface:(BOOL)arg1;
- (BOOL)showEULAWindow;
- (void)dealloc;
- (id)init;

@end

