//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <LicensingKit/ZLicensingPolicy.h>

@class NSData, NSString, ZLicenseCredential, ZLicenseKeyFormatter, ZLicensePackage, ZLicenseServer;

@interface ZLicensePackageRegistrationPolicy : ZLicensingPolicy
{
    ZLicenseKeyFormatter *formatter;
    ZLicenseServer *licenseServer;
    ZLicensePackage *package;
    ZLicenseCredential *currentCredential;
    NSString *credentialName;
    NSData *publicKey;
}

@property(retain, nonatomic) NSData *publicKey; // @synthesize publicKey;
@property(retain, nonatomic) NSString *credentialName; // @synthesize credentialName;
@property(retain, nonatomic) ZLicenseCredential *currentCredential; // @synthesize currentCredential;
@property(retain, nonatomic) ZLicensePackage *package; // @synthesize package;
@property(retain, nonatomic) ZLicenseServer *licenseServer; // @synthesize licenseServer;
- (void).cxx_destruct;
- (BOOL)applyWithUserInterface:(BOOL)arg1;
- (void)registerLicense;
- (void)idle;
- (BOOL)shouldReplaceCredential:(id)arg1;
- (BOOL)authenticateCredential:(id)arg1;
- (BOOL)validatePackage;
- (id)descriptionForError:(id)arg1;
- (id)translateError:(id)arg1;
- (id)init;

@end

