//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <LicensingKit/NSCopying-Protocol.h>
#import <LicensingKit/ZTimeLimitedCredential-Protocol.h>

@class NSDate, NSString, ZVersion;

@interface ZLicenseDescriptor : NSObject <ZTimeLimitedCredential, NSCopying>
{
    NSString *productCode;
    ZVersion *version;
    NSString *type;
    unsigned long long serialNumber;
    unsigned long long flags;
    NSDate *issueDate;
    NSDate *expiryDate;
}

+ (id)descriptorFromData:(id)arg1;
+ (id)descriptorFromString:(id)arg1;
+ (void)parseDate:(id *)arg1 fromString:(id)arg2;
+ (void)parseFlags:(unsigned long long *)arg1 fromString:(id)arg2;
+ (void)parseSerialNumber:(unsigned long long *)arg1 fromString:(id)arg2;
+ (void)parseVersion:(id *)arg1 fromString:(id)arg2;
+ (void)parseType:(id *)arg1 fromString:(id)arg2;
+ (void)parseProductCode:(id *)arg1 fromString:(id)arg2;
+ (void)initialize;
@property(retain, nonatomic) NSDate *expiryDate; // @synthesize expiryDate;
@property(retain, nonatomic) NSDate *issueDate; // @synthesize issueDate;
@property(nonatomic) unsigned long long flags; // @synthesize flags;
@property(nonatomic) unsigned long long serialNumber; // @synthesize serialNumber;
@property(retain, nonatomic) NSString *type; // @synthesize type;
@property(retain, nonatomic) ZVersion *version; // @synthesize version;
@property(retain, nonatomic) NSString *productCode; // @synthesize productCode;
- (void).cxx_destruct;
- (id)dataValue;
@property(readonly, nonatomic) NSString *stringValue;
- (id)formattedExpiryDate;
- (id)formattedIssueDate;
- (id)formattedFlags;
- (id)formattedSerialNumber;
- (id)formattedType;
- (id)formattedVersion;
- (id)formattedProductCode;
- (id)string:(id)arg1 paddedWithString:(id)arg2 toLength:(unsigned long long)arg3;
- (long long)compare:(id)arg1;
- (BOOL)isEqualToDescriptor:(id)arg1;
- (BOOL)isEqual:(id)arg1;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (BOOL)hasExpired;
- (unsigned long long)remaining;
- (unsigned long long)elapsed;
- (unsigned long long)duration;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

