//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <LicensingKit/NSCoding-Protocol.h>

@class NSData;

@interface ZLicenseCredential : NSObject <NSCoding>
{
    NSData *licenseKey;
    NSData *nodeSignature;
}

+ (id)credentialFromSerializedRepresentation:(id)arg1;
+ (void)writeCredential:(id)arg1 withName:(id)arg2 toFileAtURL:(id)arg3;
+ (id)readCredentialWithName:(id)arg1 fromFileAtURL:(id)arg2;
+ (void)writeDictionary:(id)arg1 toFileAtURL:(id)arg2;
+ (id)readDictionaryFromFileAtURL:(id)arg1;
+ (id)resetTrialURL;
+ (id)fileURL;
+ (id)fileName;
+ (id)readCredentialFromPreferencesWithName:(id)arg1;
+ (void)setCredential:(id)arg1 withName:(id)arg2;
+ (id)credentialWithName:(id)arg1;
+ (id)descriptorFromLicenseKey:(id)arg1 authenticatedWithPublicKey:(id)arg2;
+ (id)descriptorFromLicenseKey:(id)arg1;
+ (BOOL)parseLicenseKey:(id)arg1 intoDescriptor:(id *)arg2 signature:(id *)arg3;
+ (id)signDescriptor:(id)arg1 withPrivateKey:(id)arg2;
@property(retain, nonatomic) NSData *nodeSignature; // @synthesize nodeSignature;
@property(retain, nonatomic) NSData *licenseKey; // @synthesize licenseKey;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqualToCredential:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)serializedRepresentationWithName:(id)arg1;
- (id)serializedRepresentation;
- (id)authenticateWithPublicKey:(id)arg1;

@end

