//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <LicensingKit/ZTransactedObject.h>

@class NSString;

@interface ZOrderItem : ZTransactedObject
{
}

- (id)description;
@property(nonatomic) unsigned long long quantity;
@property(nonatomic) double itemAmount;
@property(nonatomic) double discountAmount;
@property(nonatomic) double grossAmount;
@property(retain, nonatomic) NSString *currency;
@property(nonatomic) unsigned long long licenseSerialNumber;
@property(nonatomic) unsigned long long orderIdentifier;
@property(retain, nonatomic) NSString *productName;
@property(nonatomic) unsigned long long productIdentifier;
@property(nonatomic) unsigned long long position;
@property(nonatomic) unsigned long long identifier;
- (id)init;
- (id)XMLRPCStructureWithOptions:(id)arg1;
- (id)initWithXMLRPCStructure:(id)arg1;

@end

