//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <LicensingKit/ZTransactedObject.h>

@class NSDate, NSString;

@interface ZOrder : ZTransactedObject
{
}

- (void)removeAllItems;
- (void)removeItem:(id)arg1;
- (void)replaceItem:(id)arg1 with:(id)arg2;
- (void)addItem:(id)arg1;
- (void)removeObjectFromItemsAtIndex:(unsigned long long)arg1;
- (void)replaceObjectInItemsAtIndex:(unsigned long long)arg1 withObject:(id)arg2;
- (void)insertObject:(id)arg1 inItemsAtIndex:(unsigned long long)arg2;
- (void)setItems:(id)arg1;
- (id)items;
- (id)description;
@property(retain, nonatomic) NSString *comments;
@property(retain, nonatomic) NSString *addressCountryCode;
@property(retain, nonatomic) NSString *addressCountry;
@property(retain, nonatomic) NSString *addressZipCode;
@property(retain, nonatomic) NSString *addressState;
@property(retain, nonatomic) NSString *addressCity;
@property(retain, nonatomic) NSString *addressStreet;
@property(retain, nonatomic) NSString *addressName;
@property(retain, nonatomic) NSString *countryCode;
@property(retain, nonatomic) NSString *phoneNumber;
@property(retain, nonatomic) NSString *emailAddress;
@property(retain, nonatomic) NSString *businessName;
@property(retain, nonatomic) NSString *lastName;
@property(retain, nonatomic) NSString *firstName;
@property(retain, nonatomic) NSDate *paymentDate;
@property(retain, nonatomic) NSString *paymentType;
@property(retain, nonatomic) NSString *paymentStatus;
@property(retain, nonatomic) NSDate *cancellationDate;
@property(nonatomic, getter=isCanceled) BOOL canceled;
@property(nonatomic) double transferAmount;
@property(retain, nonatomic) NSString *transferCurrency;
@property(nonatomic) double discountAmount;
@property(nonatomic) double shippingCharge;
@property(nonatomic) double handlingCharge;
@property(nonatomic) double tax;
@property(nonatomic) double grossAmount;
@property(nonatomic) double exchangeRate;
@property(retain, nonatomic) NSString *currency;
@property(nonatomic) double agentFee;
@property(retain, nonatomic) NSString *agentCustomerReference;
@property(retain, nonatomic) NSString *agentReceiptId;
@property(retain, nonatomic) NSString *agentTransactionType;
@property(retain, nonatomic) NSString *agentTransactionReference;
@property(retain, nonatomic) NSString *agent;
@property(retain, nonatomic) NSDate *lastModificationDate;
@property(retain, nonatomic) NSDate *creationDate;
@property(nonatomic) unsigned long long identifier;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)XMLRPCStructureWithOptions:(id)arg1;
- (id)initWithXMLRPCStructure:(id)arg1;

@end

