//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ZLicensingPolicy.h"

@class NSData, NSString, ZLicenseCredential, ZLicenseServer, ZVersion;

@interface ZOwnershipLicensingPolicy : ZLicensingPolicy
{
    ZLicenseServer *licenseServer;
    ZLicenseCredential *credential;
    NSString *credentialName;
    NSData *publicKey;
    ZVersion *productVersion;
}

+ (id)policyWithCredential:(id)arg1 name:(id)arg2 publicKey:(id)arg3;
@property(retain, nonatomic) ZVersion *productVersion; // @synthesize productVersion;
@property(retain, nonatomic) NSData *publicKey; // @synthesize publicKey;
@property(retain, nonatomic) NSString *credentialName; // @synthesize credentialName;
@property(retain, nonatomic) ZLicenseCredential *credential; // @synthesize credential;
@property(retain, nonatomic) ZLicenseServer *licenseServer; // @synthesize licenseServer;

- (void)licenseCredentialsChanged:(id)arg1;
- (BOOL)applyWithUserInterface:(BOOL)arg1;
- (BOOL)showWindowForLicenseDescriptor:(id)arg1;
- (BOOL)showExpiryWindowForLicenseDescriptor:(id)arg1;
- (void)dealloc;
- (id)init;

@end

