//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <LicensingKit/ZTransactedObject.h>

@class NSData, NSDate, NSString, ZTimePeriod, ZVersion;

@interface ZProduct : ZTransactedObject
{
}

- (id)description;
@property(nonatomic) unsigned long long registrationThreshold;
@property(nonatomic) unsigned long long users;
@property(retain, nonatomic) NSString *licenseKeyFormat;
@property(retain, nonatomic) NSData *publicKey;
@property(retain, nonatomic) NSData *privateKey;
@property(retain, nonatomic) NSDate *upgradeGracePeriodStartDate;
@property(nonatomic) unsigned long long upgradeIdentifier;
@property(retain, nonatomic) ZVersion *version;
@property(retain, nonatomic) ZTimePeriod *licensePeriod;
@property(nonatomic) unsigned long long licenseFlags;
@property(retain, nonatomic) NSString *licenseType;
@property(retain, nonatomic) NSString *code;
@property(retain, nonatomic) NSString *name;
@property(retain, nonatomic) NSDate *lastModificationDate;
@property(retain, nonatomic) NSDate *creationDate;
@property(nonatomic) unsigned long long identifier;
- (id)init;
- (id)XMLRPCStructureWithOptions:(id)arg1;
- (id)initWithXMLRPCStructure:(id)arg1;

@end

