//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <LicensingKit/ZLicensingPolicy.h>

@class NSData, ZLicenseCredential, ZLicenseDescriptor, ZLicenseServer;

@interface ZSubscriptionLicensingPolicy : ZLicensingPolicy
{
    ZLicenseServer *_licenseServer;
    NSData *_licensingKey;
    ZLicenseDescriptor *_licenseDescriptor;
    ZLicenseCredential *_credential;
    NSData *_publicKey;
}

+ (id)policyWithLicensingKey:(id)arg1 server:(id)arg2;
@property(retain, nonatomic) NSData *publicKey; // @synthesize publicKey=_publicKey;
@property(retain, nonatomic) ZLicenseCredential *credential; // @synthesize credential=_credential;
@property(retain, nonatomic) ZLicenseDescriptor *licenseDescriptor; // @synthesize licenseDescriptor=_licenseDescriptor;
@property(retain, nonatomic) NSData *licensingKey; // @synthesize licensingKey=_licensingKey;
@property(retain, nonatomic) ZLicenseServer *licenseServer; // @synthesize licenseServer=_licenseServer;
- (void).cxx_destruct;
- (BOOL)apply;
- (void)reapply;
- (void)showLicenseExpiredWindow;
- (id)initWithLicensingKey:(id)arg1 server:(id)arg2;
- (id)init;
- (BOOL)applyWithUserInterface:(BOOL)arg1;

@end

