//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ZSystemInformation : NSObject
{
}

+ (id)anonymousVariables;
+ (id)anonymousProperties;
+ (id)anonymousKeys;
+ (id)standardVariables;
+ (id)standardProperties;
+ (id)standardKeys;
+ (id)variablesFromProperties:(id)arg1;
+ (id)propertiesForKeys:(id)arg1;
+ (id)propertyForKey:(id)arg1;
+ (id)uniqueHash;
+ (id)uniqueIdentifier;
+ (id)model;
+ (id)modelTypes;
+ (id)memory;
+ (id)numberOfProcessorCores;
+ (id)processorSpeed;
+ (id)processorSubType;
+ (id)processorType;
+ (id)language;
+ (id)operatingSystemVersion;
+ (id)operatingSystemType;
+ (id)nodeKey;

@end

