//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ZSystemInformationProperty : NSObject
{
    NSString *name;
    NSString *description;
    id value;
    NSString *formattedValue;
}

@property(retain, nonatomic) NSString *formattedValue; // @synthesize formattedValue;
@property(retain, nonatomic) id value; // @synthesize value;
@property(retain, nonatomic) NSString *description; // @synthesize description;
@property(retain, nonatomic) NSString *name; // @synthesize name;
- (void).cxx_destruct;
- (id)init;
- (id)XMLRPCStructureWithOptions:(id)arg1;

@end

