//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <LicensingKit/NSCoding-Protocol.h>
#import <LicensingKit/NSCopying-Protocol.h>

@class NSDateComponents, NSString;

@interface ZTimePeriod : NSObject <NSCoding, NSCopying>
{
    long long value;
    unsigned long long unit;
}

+ (id)timePeriodWithString:(id)arg1;
+ (id)timePeriodWithYears:(long long)arg1;
+ (id)timePeriodWithMonths:(long long)arg1;
+ (id)timePeriodWithWeeks:(long long)arg1;
+ (id)timePeriodWithDays:(long long)arg1;
+ (id)timePeriodWithValue:(long long)arg1 unit:(unsigned long long)arg2;
@property(nonatomic) unsigned long long unit; // @synthesize unit;
@property(nonatomic) long long value; // @synthesize value;
@property(readonly) __weak NSString *naturalLanguageStringValue;
@property(readonly) __weak NSString *stringValue;
- (long long)compare:(id)arg1;
- (id)description;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isEqualToTimePeriod:(id)arg1;
@property(readonly) __weak NSDateComponents *dateComponents;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (id)initWithValue:(long long)arg1 unit:(unsigned long long)arg2;

@end

