//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <LicensingKit/ZLicensingPolicy.h>

@class NSData, NSString, ZLicenseServer, ZTrialPeriod;

@interface ZTrialPeriodLicensingPolicy : ZLicensingPolicy
{
    ZLicenseServer *licenseServer;
    ZTrialPeriod *trialPeriod;
    double repeatInterval;
    NSData *publicKey;
    NSString *credentialName;
    double roadblockDuration;
}

+ (id)policyWithTrialPeriod:(id)arg1 repeatingAtInterval:(double)arg2;
+ (id)policyWithTrialPeriod:(id)arg1;
@property(nonatomic) double roadblockDuration; // @synthesize roadblockDuration;
@property(retain, nonatomic) NSString *credentialName; // @synthesize credentialName;
@property(retain, nonatomic) NSData *publicKey; // @synthesize publicKey;
@property(nonatomic) double repeatInterval; // @synthesize repeatInterval;
@property(retain, nonatomic) ZTrialPeriod *trialPeriod; // @synthesize trialPeriod;
@property(retain, nonatomic) ZLicenseServer *licenseServer; // @synthesize licenseServer;
- (void).cxx_destruct;
- (void)reapply;
- (BOOL)applyWithUserInterface:(BOOL)arg1;
- (BOOL)apply;
- (BOOL)showWindow;
- (BOOL)showExpiryWindow;
- (id)init;
- (id)initWithTrialPeriod:(id)arg1 repeatInterval:(double)arg2;

@end

