//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <LicensingKit/ZUnregisterLicensePresenterInterface-Protocol.h>

@class NSString, ZLicenseCredential, ZLicenseServer;
@protocol ZUnregisterLicenseViewInterface;

@interface ZUnregisterLicensePresenter : NSObject <ZUnregisterLicensePresenterInterface>
{
    ZLicenseServer *_licenseServer;
    ZLicenseCredential *_licenseCredential;
    id <ZUnregisterLicenseViewInterface> _view;
}

@property(retain, nonatomic) id <ZUnregisterLicenseViewInterface> view; // @synthesize view=_view;
@property(retain, nonatomic) ZLicenseCredential *licenseCredential; // @synthesize licenseCredential=_licenseCredential;
@property(retain, nonatomic) ZLicenseServer *licenseServer; // @synthesize licenseServer=_licenseServer;
- (void).cxx_destruct;
- (void)disableTrial;
- (void)unregisterLicenseWithEmail:(id)arg1;
- (id)initWithLicenseServer:(id)arg1 credentials:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

