//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import <LicensingKit/NSTextFieldDelegate-Protocol.h>
#import <LicensingKit/ZUnregisterLicenseViewInterface-Protocol.h>

@class NSButton, NSProgressIndicator, NSString, NSTextField, ZLicenseKeyFormatter;
@protocol ZUnregisterLicensePresenterInterface;

@interface ZUnregisterLicenseWindowController : NSWindowController <ZUnregisterLicenseViewInterface, NSTextFieldDelegate>
{
    ZLicenseKeyFormatter *formatter;
    id <ZUnregisterLicensePresenterInterface> _presenter;
    NSTextField *_emailField;
    NSTextField *_licenseKeyField;
    NSButton *_unregisterButton;
    NSProgressIndicator *_spinner;
    NSButton *_cancelButton;
}

@property __weak NSButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property __weak NSProgressIndicator *spinner; // @synthesize spinner=_spinner;
@property __weak NSButton *unregisterButton; // @synthesize unregisterButton=_unregisterButton;
@property __weak NSTextField *licenseKeyField; // @synthesize licenseKeyField=_licenseKeyField;
@property __weak NSTextField *emailField; // @synthesize emailField=_emailField;
@property(retain, nonatomic) id <ZUnregisterLicensePresenterInterface> presenter; // @synthesize presenter=_presenter;
- (void).cxx_destruct;
- (BOOL)NSStringIsValidEmail:(id)arg1;
- (void)controlTextDidChange:(id)arg1;
- (void)enableControls;
- (void)unregisterWrongEmail;
- (void)unregisterFailed;
- (void)unregisterSucceeded;
- (void)cancelClick:(id)arg1;
- (void)closeWindow:(long long)arg1;
- (void)unregisterClicked:(id)arg1;
- (id)init;
- (id)initWithLicenseServer:(id)arg1 credential:(id)arg2;
- (void)windowDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

